### Connection route - test mail error
POST http://localhost:5050/admin-signin
Content-Type: application/json

{
    "mail": "toto@gmail.com",
    "password": "Jesuis-benoit35"
}

### Connection route - test password error
POST http://localhost:5050/admin-signin
Content-Type: application/json

{
    "mail": "benoit.doe@gmail.com",
    "password": "Jesuis-toto11"
}

### Connection route - test OK
POST http://localhost:5050/admin-signin
Content-Type: application/json

{
    "mail": "benoit.doe@gmail.com",
    "password": "toto"
}

### Route : Modify password
POST http://localhost:5050/admin-logged/1
Content-Type: application/json

{
    "userId" : 1,
    "newPassword": "toto",
    "newPasswordConfirm": "toto"
}
